services:
  frontend:
    build:
      context: .
      dockerfile: dockerfiles/frontend.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data/uploads:/app/data/uploads
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
      - STREAMLIT_SERVER_PORT=8501

  backend:
    build:
      context: .
      dockerfile: dockerfiles/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - vector_db
      - financial_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB_HOST=vector_db
      - VECTOR_DB_PORT=8080
      - DATABASE_URL=sqlite:///app/data/financial_db.sqlite

  document_processor:
    build:
      context: .
      dockerfile: dockerfiles/document_processor.Dockerfile
    volumes:
      - ./data:/app/data
      - ./data/document_drop:/app/document_drop
    depends_on:
      - vector_db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTOR_DB_HOST=vector_db
      - VECTOR_DB_PORT=8080
      - WATCH_FOLDER=/app/document_drop

  vector_db:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8080:8080"
    volumes:
      - chroma_data:/chroma/chroma

  financial_db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/data
    command: ["sqlite3", "/data/financial_db.sqlite"]

volumes:
  chroma_data: